services:
  app:
    build: ./
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/datcao
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - datcao-network
  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: datcao
    networks:
      - datcao-network

volumes:
  pg-data:

networks:
  datcao-network:
    driver: bridge
